### ISSUE TITLE
add tf? 

### ISSUE THREAD

**Issue by CaptD** [jstnhuang/ros-rviz#21]
Hi Justin,

I found your very nice work on roscon, and had no problem setting it up by following the detailed wiki.

I am wondering if you plan to add tf for visualization.

Thanks,
Jin

**Comment by jstnhuang** [comment]
A TF display would be nice. Unfortunately, I can't say for sure if I'll implement it. Of course, pull requests are welcome :).

If you really need to visualize TF frames, it is possible to simulate it using markers, of course.

**Comment by chapulina** [comment]
FYI, we'll start working on it and may have a PR for you soon if you're interested :relaxed:

**Comment by jstnhuang** [comment]
Closed by #26
