### ISSUE TITLE
Add image display

### ISSUE THREAD

**Issue by jstnhuang** [jstnhuang/ros-rviz#6]

**Comment by jstnhuang** [comment]
Probably not going to do this since images can be viewed from the web video server easily enough

**Comment by chapulina** [comment]
FYI, @jubeira started working on this on our fork and we're planning on making a PR back upstream soon if you're interested :wink: 

https://github.com/osrf/polymer-ros-rviz/pull/7

**Comment by jstnhuang** [comment]
Closed by #25
